BigfootSightings/blueprints/Login/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user

from BigfootSightings.forms import UserLoginForm, UserSignupForm, BackToMainForm
from BigfootSightings.queries import get_user_by_user_name, insert_user
from BigfootSightings.models import User

Login = Blueprint("Login", __name__)


@Login.route("/")
@Login.route("/home")
def home():
    return render_template("pages/home.html")


@Login.route("/backToMainFromSignup", methods=["GET", "POST"])
def backToMainFromSignup():
    form = BackToMainForm()
    if request.method == "POST":
        if form.validate_on_submit():
            return redirect(url_for("Login.home"))

    return render_template("pages/signup-landing.html", form=form)


@Login.route("/backToMainFromLogin", methods=["GET", "POST"])
def backToMainFromLogin():
    form = BackToMainForm()
    if request.method == "POST":
        if form.validate_on_submit():
            return redirect(url_for("Login.home"))

    return render_template("pages/login-landing.html", form=form)


@Login.route("/about")
def about():
    return render_template("pages/about.html")


@Login.route("/style-guide")
def style_guide():
    return render_template("pages/style-guide.html")


@Login.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("Login.home"))
    form = UserLoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            user = get_user_by_user_name(username)
            if user and password == form.password.data:

                login_user(user, remember=True)

                next_page = request.args.get("next")

                return (
                    redirect(next_page)
                    if next_page
                    else redirect(url_for("Login.backToMainFromLogin"))
                )
    return render_template("pages/login.html", form=form)


@Login.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("Login.home"))
    form = UserSignupForm()
    if request.method == "POST":
        if form.validate_on_submit():

            user = get_user_by_user_name(form.username.data)

            if user is None and (form.password.data == form.password_repeat.data):

                user_data = {
                    "username": form.username.data,
                    "password": form.password.data,
                }

                user = User(user_data)

                insert_user(user)

                user = get_user_by_user_name(form.username.data)

                if user:
                    login_user(user, remember=True)
                    next_page = request.args.get("next")
                    return (
                        redirect(next_page)
                        if next_page
                        else redirect(url_for("Login.backToMainFromSignup"))
                    )
    return render_template("pages/signup.html", form=form)


@Login.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("Login.login"))

BigfootSightings/blueprints/Sightings/routes.py
from flask import render_template, redirect, url_for, request, Blueprint
from flask_login import login_required, current_user

from BigfootSightings.forms import AddSightingForm, SearchSightingForm, BackToMainForm
from BigfootSightings.models import Sighting
from BigfootSightings.queries import (
    insert_sighting,
    get_all_sightings,
    search_sightings,
    show_timezone,
)

Sightings = Blueprint("Sighting", __name__)


@Sightings.route("/backToMainFromAdd", methods=["GET", "POST"])
def backToMainFromAdd():
    form = BackToMainForm()
    if request.method == "POST":
        if form.validate_on_submit():
            return redirect(url_for("Login.login"))  # Change endpoint to 'Login.login'

    return render_template("pages/add-sighting-landing.html", form=form)


@Sightings.route("/add-sighting", methods=["GET", "POST"])
@login_required
def add_sighting():
    form = AddSightingForm()
    if request.method == "POST":
        if form.validate_on_submit():

            sighting_data = {}
            sighting_data["title"] = form.title.data
            sighting_data["latitude"] = form.latitude.data
            sighting_data["longitude"] = form.longitude.data

            username = current_user.username

            insert_sighting(username, sighting_data)

            next_page = request.args.get("next")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("Sighting.backToMainFromAdd"))
            )

    return render_template("pages/add-sighting.html", form=form)


@Sightings.route("/all-sightings", methods=["GET", "POST"])
def all_sightings():

    timezone = show_timezone()
    form = SearchSightingForm()

    if request.method == "POST":

        if form.validate_on_submit():
            if form.reset.data:
                sightings = get_all_sightings()
                return render_template(
                    "pages/all-sightings.html",
                    sightings=sightings,
                    form=form,
                    timezone=timezone,
                )

            sightings = search_sightings(
                search_text=form.search_text.data,
                username=form.username.data,
                lat=form.lat.data,
                long=form.long.data,
                location_id=form.location_id.data,
                time=form.date.data,
                country=form.country.data,
                state=form.state.data,
                city=form.city.data,
            )
    else:
        sightings = get_all_sightings()
    return render_template(
        "pages/all-sightings.html", sightings=sightings, form=form, timezone=timezone
    )

BigfootSightings/templates/components/footer.html
<footer>
    <div>
        <span>© BigfootSightings</span>
        <a href="{{ url_for('Login.about') }}">About</a>
    </div>
</footer>

BigfootSightings/templates/components/macros.html
{% macro cta_button (class='') %}
    <a class="btn {{ class }}" href="{{ url_for('Produce.produce') }}">
        <span>
            <img src="{{ url_for('static', filename='images/icons/cart.svg') }}" alt="cart" class="icon">
            Start shopping
        </span>
    </a>
{% endmacro %}


{% macro form_errors (errors=[]) %}
    {% for error in errors %}
        <span class="text--red">{{ error }}</span>
    {% endfor %}
{% endmacro %}




{% macro sighting_card (sighting=None, timezone=None) %}
    <div class="card">
        <div class="card__info">
            <p>Nr.: {{ sighting.nr }}</p>
            <p>Reported by: {{ sighting.username }}</p>
            <p>Description: {{ sighting.title }}</p>
            <p>Report time in local time ({{ timezone }}) +/- offset  from UTC: {{ sighting.report_time }}</p>
            <p>Latitude: {{ sighting.latitude}}</p>
            <p>Longitude: {{ sighting.longitude}}</p>
            <p>Location id: {{sighting.location_id}}</p>
            <p>Country: {{sighting.country}}</p>
            <p>State: {{sighting.state_name}}</p>
            <p>City: {{sighting.city}}</p>
        </div>

    </div>
{% endmacro %}

BigfootSightings/templates/components/navbar.html
<nav>
    <div>
        <div class="links-wrapper">
            <a href="{{ url_for("Login.home") }}">Home</a>
            <a href="{{ url_for("Sighting.add_sighting") }}">Add Bigfoot sightings</a>
            <a href="{{ url_for("Sighting.all_sightings") }}">All Bigfoot sightings</a>
        </div>

        <div class="links-wrapper">
            {% if current_user.is_authenticated %}
                <a href="{{ url_for("Login.logout") }}">Logout</a>
            {% else %}
                <a class="text--gray" href="{{ url_for("Login.signup") }}">Sign up</a>
                <a href="{{ url_for("Login.login") }}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>